# script to convert xml bounding box annotations (as generated by LabelImg et al) into csv for use with retinanet
import os
import xml.etree.ElementTree as ET

def xml2line(xmlPth):
    tree = ET.parse(xmlPth)
    root = tree.getroot()
    fname = root.find('filename').text
    lines = []

    for object in root.iter('object'):
        labelname = object.find('name').text
        for element in object.find('bndbox'):
            if element.tag=='xmin':
                xmin = element.text

            if element.tag=='xmax':
                xmax = element.text

            if element.tag=='ymin':
                ymin = element.text

            if element.tag=='ymax':
                ymax = element.text

        # print('xmin: {0}, ymin: {1}, xmax: {2}, ymax: {3}'.format(xmin,ymin,xmax,ymax))
        line = fname + ',' + xmin + ',' + ymin + ',' + xmax + ',' + ymax + ',' + labelname
        lines.append(line)# print(line)
    return lines


xmlPth = '/home/nader/scripts/retinanet_scripts/urchins/PR_20090613_132534_044_LC16.xml'



lines=xml2line(xmlPth)
print(lines)